export const FETCH_WEATHER_DAY = 'FETCH_WEATHER_DAY';
export const ADD_WEATHER_DAY = 'ADD_WEATHER_DAY';
export const FETCH_WEATHER_WEEK = 'FETCH_WEATHER_WEEK';
export const ADD_WEATHER_WEEK = 'ADD_WEATHER_WEEK';
export const ADD_DETAILED_WEEK_DAY = 'ADD_DETAILED_WEEK_DAY';
export const ADD_CITIES = 'ADD_CITIES';

